# Generated by Django 5.2.9 on 2025-12-03 16:13

import app.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(help_text='Product image', upload_to='products/', validators=[app.models.validate_image_file, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])]),
        ),
        migrations.CreateModel(
            name='OrderQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code_image', models.ImageField(help_text='QR code image file', upload_to='qr_codes/')),
                ('qr_data', models.TextField(help_text='QR code data/content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='QR code expiration time (5 minutes after creation)')),
                ('is_used', models.BooleanField(default=False, help_text='Whether QR code has been used for payment')),
                ('used_at', models.DateTimeField(blank=True, help_text='Timestamp when payment was confirmed', null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qr_code', to='app.order')),
            ],
            options={
                'verbose_name': 'Order QR Code',
                'verbose_name_plural': 'Order QR Codes',
                'ordering': ['-created_at'],
            },
        ),
    ]
