# Generated by Django 5.2.9 on 2025-12-04 20:57

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_image_orderqrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for the slide', max_length=200, null=True)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subtitle/description', max_length=300, null=True)),
                ('slide_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('url', 'External URL')], default='image', help_text='Type of media for this slide', max_length=10)),
                ('image', models.ImageField(blank=True, help_text="Upload an image for this slide (if slide type is 'Image')", null=True, upload_to='hero_slides/', validators=[app.models.validate_image_file, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif'])])),
                ('video', models.FileField(blank=True, help_text="Upload a video for this slide (if slide type is 'Video')", null=True, upload_to='hero_slides/videos/', validators=[app.models.validate_video_file, django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov'])])),
                ('external_url', models.URLField(blank=True, help_text="External URL for image or video (if slide type is 'URL')", null=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this slide in the carousel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
