# Generated by Django 5.2.9 on 2025-12-05 15:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Commission rate as percentage (e.g., 5.00 for 5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promoter',
                'verbose_name_plural': 'Promoters',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='is_suspicious',
            field=models.BooleanField(default=False, help_text='Flagged as suspicious order'),
        ),
        migrations.AddField(
            model_name='order',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Manually verified by admin'),
        ),
        migrations.AddField(
            model_name='order',
            name='suspicious_reason',
            field=models.CharField(blank=True, help_text='Reason for flagging as suspicious', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes about verification', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('verified', 'Verified'), ('suspicious', 'Suspicious - Needs Review'), ('rejected', 'Rejected')], default='pending', help_text='Order verification status', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='verified_by',
            field=models.CharField(blank=True, help_text='Admin who verified this order', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='promocode',
            name='promoter',
            field=models.ForeignKey(blank=True, help_text='Promoter who owns this promo code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_codes', to='app.promoter'),
        ),
    ]
