# Generated by Django 5.2.9 on 2025-12-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_promoter_order_is_suspicious_order_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cod_delivery_notes',
            field=models.TextField(blank=True, help_text='Notes about COD delivery/payment', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_received',
            field=models.BooleanField(default=False, help_text='For COD: Payment received from customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_received_at',
            field=models.DateTimeField(blank=True, help_text='When payment was received', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_received_by',
            field=models.CharField(blank=True, help_text='Admin/staff who confirmed payment', max_length=200, null=True),
        ),
    ]
