# Generated by Django 5.2.9 on 2025-12-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_received',
            field=models.BooleanField(default=False, help_text='Customer has received the order'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_received_at',
            field=models.DateTimeField(blank=True, help_text='When customer received the order', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_received_by',
            field=models.CharField(blank=True, help_text='Who confirmed customer received (driver/staff)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_received_notes',
            field=models.TextField(blank=True, help_text='Notes about customer receiving the order', null=True),
        ),
    ]
