# Generated by Django 5.2.9 on 2025-12-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_customer_received_order_customer_received_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_received',
            field=models.BooleanField(default=False, help_text='Whether the customer has physically received the order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_received_at',
            field=models.DateTimeField(blank=True, help_text='When the customer received the order', null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_received_by',
            field=models.CharField(blank=True, help_text='Admin/staff who confirmed customer received', max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='customer_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['updated_at'], name='customer_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_phone'], name='order_customer_phone_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='order_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_received'], name='order_payment_received_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer_received'], name='order_customer_received_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'customer_received'], name='order_status_received_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['payment_method', 'status'], name='order_payment_status_idx'),
        ),
    ]
