# Generated by Django 5.2.9 on 2025-12-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_order_customer_received_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_payment_status_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='app_custome_phone_1cde69_idx',
            old_name='customer_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='app_custome_updated_4bb7c0_idx',
            old_name='customer_updated_at_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='app_order_custome_44e875_idx',
            old_name='order_customer_phone_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='app_order_payment_a13504_idx',
            old_name='order_payment_received_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='app_order_custome_20bee9_idx',
            old_name='order_customer_received_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='app_order_created_56751d_idx',
            old_name='order_created_at_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='app_order_status_9cf978_idx',
            old_name='order_status_received_idx',
        ),
        migrations.AlterField(
            model_name='orderqrcode',
            name='expires_at',
            field=models.DateTimeField(help_text='QR code expiration time (10 minutes after creation)'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['created_at'], name='app_custome_created_37a0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='app_order_status_4eece7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='app_order_order_n_9a87c0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderqrcode',
            index=models.Index(fields=['expires_at', 'is_used'], name='app_orderqr_expires_d11cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='orderqrcode',
            index=models.Index(fields=['order'], name='app_orderqr_order_i_26df97_idx'),
        ),
    ]
