"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (if python-dotenv is installed)
try:
    from dotenv import load_dotenv
    load_dotenv(BASE_DIR / '.env')
except ImportError:
    # python-dotenv not installed, will use system environment variables
    pass

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Use environment variable in production: export SECRET_KEY='your-secret-key'
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-wr-e*gp=1*s26id!o2h#tik($w^#olr20*8wn98aplo#wma%!u')

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=False in production: export DEBUG='False'
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# ALLOWED_HOSTS: Set in production: export ALLOWED_HOSTS='yourdomain.com,www.yourdomain.com'
# For local testing on mobile devices, allow all hosts in development
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else ['*'] if DEBUG else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',  # CORS handling
    'import_export',  # Excel/CSV import/export
    'channels',  # WebSocket support
    'app',
]

# Add rate limiting only in production (with proper cache)
# In development, rate limiting decorators are handled gracefully in views.py
# and won't enforce limits
if not DEBUG:
    INSTALLED_APPS.append('django_ratelimit')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Static files serving (production)
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Multi-language support
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Security middleware
    'app.middleware.SecurityHeadersMiddleware',
    'app.middleware.RequestSizeLimitMiddleware',
    # Optional: Uncomment to enable IP whitelist for admin
    # 'app.middleware.IPWhitelistMiddleware',
    # Performance optimization middleware
    'app.middleware.CompressionMiddleware',
    'app.middleware.CacheControlMiddleware',
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# PostgreSQL Database Configuration
# Use environment variable DATABASE_URL if set, otherwise use PostgreSQL
try:
    import dj_database_url
    # Try to get DATABASE_URL from environment
    database_url = os.environ.get('DATABASE_URL')
    if database_url:
        # Use environment variable (for production/cloud)
        DATABASES = {
            'default': dj_database_url.config(
                default=database_url,
                conn_max_age=600 if not DEBUG else 0,
            )
        }
    else:
        # Check if PostgreSQL env vars are set
        db_name = os.environ.get('DB_NAME')
        db_user = os.environ.get('DB_USER')
        db_password = os.environ.get('DB_PASSWORD')
        
        # Use PostgreSQL only if env vars are explicitly set
        if db_name and db_user and db_password:
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.postgresql',
                    'NAME': db_name,
                    'USER': db_user,
                    'PASSWORD': db_password,
                    'HOST': os.environ.get('DB_HOST', 'localhost'),
                    'PORT': os.environ.get('DB_PORT', '5432'),
                }
            }
        else:
            # Fallback to SQLite if PostgreSQL env vars not set
            DATABASES = {
                'default': {
                    'ENGINE': 'django.db.backends.sqlite3',
                    'NAME': BASE_DIR / 'db.sqlite3',
                }
            }
except ImportError:
    # Fallback to PostgreSQL if dj-database-url not installed
    # Use PostgreSQL only if env vars are explicitly set
    db_name = os.environ.get('DB_NAME')
    db_user = os.environ.get('DB_USER')
    db_password = os.environ.get('DB_PASSWORD')
    
    if db_name and db_user and db_password:
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': db_name,
                'USER': db_user,
                'PASSWORD': db_password,
                'HOST': os.environ.get('DB_HOST', 'localhost'),
                'PORT': os.environ.get('DB_PORT', '5432'),
            }
        }
    else:
        # Fallback to SQLite if PostgreSQL env vars not set
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

# Import-Export Settings (for Excel/CSV import with Khmer text support)
IMPORT_EXPORT_USE_TRANSACTIONS = True
IMPORT_EXPORT_SKIP_ADMIN_LOG = False
IMPORT_EXPORT_CHUNK_SIZE = 100

# Encoding settings for Excel exports (Khmer text support)
IMPORT_EXPORT_EXPORT_FORMATS = [
    ('xlsx', 'Excel (.xlsx)'),
    ('csv', 'CSV (.csv)'),
    ('json', 'JSON'),
    ('tsv', 'TSV'),
]

# Ensure UTF-8 encoding for exports
DEFAULT_CHARSET = 'utf-8'
# For development: Use dummy cache (rate limiting won't work but server will run)
# For production: Use Redis or Memcached (recommended)
# Example Redis config:
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.redis.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#     }
# }
if DEBUG:
    # Development: Use dummy cache to avoid errors
    # Rate limiting decorators will be ignored in development
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.dummy.DummyCache',
        }
    }
else:
    # Production: Use Redis (configure based on your setup)
    # IMPORTANT: Install and configure Redis for production!
    try:
        import django_redis
        CACHES = {
            'default': {
                'BACKEND': 'django_redis.cache.RedisCache',
                'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
                'OPTIONS': {
                    'CLIENT_CLASS': 'django_redis.client.DefaultClient',
                    'COMPRESSOR': 'django_redis.compressors.zlib.ZlibCompressor',
                    'IGNORE_EXCEPTIONS': True,
                },
                'KEY_PREFIX': 'madamda',
                'TIMEOUT': 300,
            }
        }
        # Use cache for sessions in production
        SESSION_ENGINE = 'django.contrib.sessions.backends.cache'
        SESSION_CACHE_ALIAS = 'default'
    except ImportError:
        # Fallback if django-redis not installed
        CACHES = {
            'default': {
                'BACKEND': 'django.core.cache.backends.redis.RedisCache',
                'LOCATION': os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/1'),
            }
        }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', 'English'),
    ('kh', 'Khmer'),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'Asia/Phnom_Penh'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Performance Optimization Settings
# Cache static files for 1 year (31536000 seconds)
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'

# Browser caching for static files
if not DEBUG:
    # In production, use these headers (configure in your web server)
    # For development, Django handles this automatically
    pass

# Security and Performance Headers
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

# Additional Security Settings
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# Rate Limiting (using Django's built-in)
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'

# CSRF Settings
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SECURE = not DEBUG  # Secure in production
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if os.environ.get('CSRF_TRUSTED_ORIGINS') else []

# Session Security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE = not DEBUG  # Secure in production
SESSION_COOKIE_AGE = 3600  # 1 hour
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_SAVE_EVERY_REQUEST = True  # Refresh session on each request

# File Upload Security
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = 1000

# Request Security
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https') if not DEBUG else None

# CORS Settings (if needed for API)
CORS_ALLOWED_ORIGINS = os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if os.environ.get('CORS_ALLOWED_ORIGINS') else []
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_METHODS = ['GET', 'POST', 'OPTIONS']
CORS_ALLOW_HEADERS = ['Content-Type', 'X-CSRFToken']

# Admin Security
ADMIN_URL = os.environ.get('ADMIN_URL', 'admin/')  # Change default admin URL

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'security': {
            'format': 'SECURITY {asctime} {levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'django.log',
            'formatter': 'verbose',
        },
        'security_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'security.log',
            'formatter': 'security',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'django.security': {
            'handlers': ['security_file', 'console'],
            'level': 'WARNING',
            'propagate': True,
        },
        'app': {
            'handlers': ['file', 'console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Create logs directory if it doesn't exist
import os
logs_dir = BASE_DIR / 'logs'
if not logs_dir.exists():
    os.makedirs(logs_dir, exist_ok=True)

# Bakong API Configuration
BAKONG_API_BASE = 'https://bakongapi.com'
BAKONG_ID = 'vicheka_yeun@wing'  # ⚠️ This is a Wing account - may only accept Wing payments
                                  # For multi-bank support, use a universal Bakong account (not @wing/@aba/@acleda)
                                  # Or register as merchant with each bank you want to accept payments from
BAKONG_MERCHANT_NAME = 'MADAM DA'  # Note: Must match exactly what's in your Bakong dashboard whitelist

# Telegram Bot Configuration for Order Notifications
# IMPORTANT: If you have TELEGRAM_BOT_TOKEN in environment variables, it will override this
# Make sure your environment variable matches the correct token!
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '8319720413:AAEeTcPJ11TyB-_h7wQ7tYi_8dCj6PzWwkM')
TELEGRAM_CHAT_ID = os.environ.get('TELEGRAM_CHAT_ID', '-4974214796')  # MADAM DA ORDER group chat ID
TELEGRAM_ENABLED = bool(TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Suppress django-ratelimit cache warnings in development
# These are expected when using dummy cache
if DEBUG:
    import logging
    logging.getLogger('django_ratelimit').setLevel(logging.ERROR)

# Django Channels Configuration for WebSocket
ASGI_APPLICATION = 'project.asgi.application'

# Channel Layers Configuration (Redis for WebSocket)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [('127.0.0.1', 6379)],
        },
    },
}
